version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: quotebot-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quotebot
    volumes:
      - ./docker/schema.sql:/docker-entrypoint-initdb.d/init-data.sql
